
add_library(usher-lib
src/matUtils/uncertainty.cpp
src/matUtils/extract.cpp
src/matUtils/translate.cpp
src/matUtils/filter.cpp
src/matUtils/annotate.cpp
src/matUtils/mask.cpp
src/matUtils/describe.cpp
src/matUtils/introduce.cpp
src/matUtils/select.cpp
src/matUtils/convert.cpp
src/matUtils/summary.cpp
src/matUtils/merge.cpp
src/usher_mapper.cpp
src/usher_common.cpp
src/check_samples_place/check_samples.cpp
src/check_samples_place/import_vcf.cpp
src/ripples/ripples_fast/ripples_mapper.cpp
src/ripples/ripples_fast/ripple_aux.cpp
src/ripples/ripples_fast/ripple_merger.cpp
src/matOptimize/main_helper.cpp
src/matOptimize/Profitable_Moves_Enumerators/process_terminal_nodes.cpp
src/matOptimize/Profitable_Moves_Enumerators/Profitable_Moves_Enumerators-debug.cpp
src/matOptimize/Profitable_Moves_Enumerators/process_LCA.cpp
src/matOptimize/Profitable_Moves_Enumerators/Profitable_Moves_Enumerator.cpp
src/matOptimize/Profitable_Moves_Enumerators/process_inidividual_mutation.cpp
src/matOptimize/Profitable_Moves_Enumerators/downward_integrated.cpp
src/matOptimize/Profitable_Moves_Enumerators/process_intermediate_node.cpp
src/matOptimize/Profitable_Moves_Enumerators/check_move_profitable_dst_branch.cpp
src/matOptimize/Profitable_Moves_Enumerators/upward_integrated.cpp
src/matOptimize/Profitable_Moves_Enumerators/range_tree.cpp
src/matOptimize/Profitable_Moves_Enumerators/check_move_profitable_LCA.cpp
src/matOptimize/Profitable_Moves_Enumerators/check_move_profitable.cpp
src/matOptimize/main_load_tree.cpp
src/matOptimize/detailed_mutations_load.cpp
src/matOptimize/mutation_annotated_tree_nuc_util.cpp
src/matOptimize/Mutation_Collection.cpp
src/matOptimize/priority_conflict_resolver.cpp
src/matOptimize/condense.cpp
src/matOptimize/detailed_mutations_store.cpp
src/matOptimize/import_vcf_fast.cpp
src/matOptimize/optimize_tree.cpp
src/matOptimize/check_samples.cpp
src/matOptimize/mutation_annotated_tree.cpp
src/matOptimize/transpose_vcf/transposed_vcf_patch.cpp
src/matOptimize/mutation_annotated_tree_node.cpp
src/matOptimize/Fitch_Sankoff.cpp
src/matOptimize/mutation_annotated_tree_load_store.cpp
src/matOptimize/VCF_load_tree.cpp
#src/matOptimize/priority_conflict_resolver_cross_only.cpp
src/matOptimize/apply_move/move_node_no_reassign.cpp
src/matOptimize/apply_move/forward_pass.cpp
src/matOptimize/apply_move/one_level_fitch_sankoff.cpp
src/matOptimize/apply_move/one_level_fitch_sankoff_binary.cpp
src/matOptimize/apply_move/backward_pass.cpp
src/matOptimize/apply_move/apply_move.cpp
src/matOptimize/apply_move/debug.cpp
src/mutation_annotated_tree.cpp
src/usher-sampled/fix_par_mut.cpp
src/usher-sampled/sampler.cpp
src/usher-sampled/static_tree_mapper/build_idx.cpp
src/usher-sampled/static_tree_mapper/search.cpp
src/usher-sampled/Min_back_FS.cpp
src/usher-sampled/import_vcf.cpp
src/usher-sampled/wait_debug.cpp
src/usher-sampled/place_sample_follower.cpp
src/usher-sampled/place_sample.cpp
src/usher-sampled/main_mapper.cpp
src/usher-sampled/testers.cpp
src/usher-sampled/utils.cpp
src/usher-sampled/place_sample_shared.cpp
src/usher-sampled/multiple_placement.cpp)

target_include_directories(usher-lib PUBLIC "${PROJECT_BINARY_DIR}")
target_compile_options(usher-lib PRIVATE -DTBB_SUPPRESS_DEPRECATED_MESSAGES)
target_link_libraries(usher-lib PRIVATE stdc++  ${Boost_LIBRARIES} ${TBB_IMPORTED_TARGETS} ${Protobuf_LIBRARIES} ZLIB::ZLIB  ${MPI_CXX_LIBRARIES} ${MPI_CXX_LINK_FLAGS} ${ISAL_LIB})
