name: larch-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # larch
  - cmake=3.19.6
  - make
  - cxx-compiler
  - openmpi
  - openmpi-mpicc
  - openmpi-mpicxx
  - boost-cpp
  - automake
  - autoconf
  - libtool
  - yasm
  - ucx
  - zlib
  - git-lfs
  # development
  - git
  - mafft
  - python
  - rsync
  - wget
  - openssh
  - gdb
  - bzip2
  - backports.lzma
  - protobuf=3.12.3
  # conda packaging
  - conda-build
  - conda-verify
  - anaconda-client
