{% set name = "larch" %}
{% set package_name = "larch-phylo" %}
{% set src = environ.get('LARCH_SRC', 'local') %}
{% set git_commit = environ.get('LARCH_COMMIT', 'main') %}
{% set version = environ.get('LARCH_VERSION', '0.1.0') %}
{% set hash = environ.get('LARCH_HASH', 'f09851e89217b688c9b012da0161cadbc88b5692a9c823b44b83c2c129a5762d') %}
{% set include_tests = environ.get('LARCH_INCLUDE_TEST', 'false') %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  {% if src == 'local' %}
  # method 1: use local repo
  path: ../
  {% elif src == 'remote' %}
  # method 2: use online repo
  git_url: https://github.com/matsengrp/larch.git
  git_rev: {{ git_commit }}
  git_submodules: true
  {% elif src == 'release' %}
  # method 3: use release tarball
  url: https://github.com/matsengrp/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ hash }}
  {% endif %}

build:
  number: 0
  skip: true # [win or osx]

requirements:
  build:
    - python
    - gcc >=12.4.0,<14.0.0
    - gxx >=12.4.0,<14.0.0
    - cmake =3.19.6
    - make
    - openmpi >=4.1.0,<5.0
    - openmpi-mpicc >=4.1.0,<5.0
    - openmpi-mpicxx >=4.1.0,<5.0
    - automake
    - autoconf
    - libtool
    - yasm
    - openssh
    - protobuf

    - openmpi >=4.1.0,<5.0
    - boost-cpp =1.76
    - ucx >=1.16.0
    - zlib >=1.2.11

  run:
    - openmpi >=4.1.0,<5.0
    - boost-cpp =1.76
    - ucx >=1.16.0
    - zlib >=1.2.11

test:
  commands:
    - larch-usher --version
    - larch-dagutil --version
    - larch-dag2dot --version

about:
  home: https://github.com/matsengrp/larch
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: 'Phylogenetic tool for exploring tree space of mutation annotated DAG/trees through SPR moves'
  description: |
    Phylogenetic tool for exploring tree space of mutation annotated DAG/trees through SPR moves.
  doc_url: https://github.com/matsengrp/larch/blob/main/README.md
  dev_url: https://github.com/matsengrp/larch

extra:
  recipe-maintainers:
    - matsen
    - davidrich27
    - marybarker
