{{% set name = "larch" %}}
{{% set full_name = "larch-usher" %}}
{{% set version = "0.1" %}}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: null
  url: https://github.com/matsengrp/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  git_url: null
  sha256: null

build:
  number: 0
  script: build.sh
  # string: "custom_build_string"


requirements:
  build:
    - cmake=3.16
    - make
    - cxx-compiler
    - openmpi
    - openmpi-mpicc
    - openmpi-mpicxx
    - boost-cpp
    - automake
    - autoconf
    - libtool
    - yasm
    - ucx
    - zlib
  run:
    - openmpi
    - openmpi-mpicc
    - openmpi-mpicxx
    - boost-cpp
    - ucx
    - zlib

test:
  commands:
    - larch-test -tag slow
  files:
    - data/


about:
  home: https://github.com/matsengrp/larch
  license: GNU General Public License
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Tool for exploring tree space of DAG/tree through SPR moves'
  description: |
    Tool for exploring tree space of DAG/tree through SPR moves
  doc_url: https://github.com/matsengrp/larch/blob/main/README.md
  dev_url: https://github.com/matsengrp/larch
