
{% set name = "larch" %}
{% set version = environ.get('VERSION', '0.0.0') %}
{% set git_rev = environ.get('GIT_COMMIT', 'main') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # method 1: use local repo
  # path: ../
  # method 2: use online repo
  git_url: git@github.com:matsengrp/larch.git
  # git_rev: {{ git_rev }}
  git_rev: main
  git_submodules: true

build:
  number: 0
  skip: true # [win]

requirements:
  build:
    - cmake=3.19.6
    - make
    # - cxx-compiler
    - openmpi
    - openmpi-mpicc
    - openmpi-mpicxx
    - boost-cpp=1.76
    - automake
    - autoconf
    - libtool
    - yasm
    - ucx
    - zlib

    - gcc
    - gxx
    - binutils
    - binutils_impl_linux-64
    - binutils_linux-64
    - gdb
    - libstdcxx-ng
    - libgcc-ng
    - libgomp
    - libgfortran-ng
    - libgfortran5
    - libedit
    - libffi
    - expat
    - libuuid
    - libiconv
    - libzlib
    - perl
    - gettext
    - libasprintf
    - libtool
    - kernel-headers_linux-64
    - rdma-core
    - openssl
    - keyutils

  run:
    - openmpi
    - openmpi-mpicc
    - openmpi-mpicxx
    - boost-cpp=1.76
    - ucx
    - zlib

    - binutils
    - binutils_impl_linux-64
    - binutils_linux-64
    - gdb
    - libstdcxx-ng
    - libgcc-ng
    - libgomp
    - libgfortran-ng
    - libgfortran5
    - libedit
    - libffi
    - expat
    - libuuid
    - libiconv
    - libzlib
    - perl
    - gettext
    - libasprintf
    - libtool
    - kernel-headers_linux-64
    - rdma-core
    - openssl
    - keyutils

test:
  commands:
    - larch-usher --version
    - ln -s ${SRC_DIR}/data 
    - larch-test -tag slow

about:
  home: https://github.com/matsengrp/larch
  license: GNU General Public License
  license_family: GPL
  license_file: LICENSE
  summary: 'Tool for exploring tree space of DAG/tree through SPR moves'
  description: |
    Tool for exploring tree space of DAG/tree through SPR moves
  doc_url: https://github.com/matsengrp/larch/blob/main/README.md
  dev_url: https://github.com/matsengrp/larch
