{% set name = "larch-phylo" %}
{% set src = environ.get('LARCH_SRC', 'local') %}
{% set git_commit = environ.get('LARCH_COMMIT', 'main') %}
{% set version = environ.get('LARCH_VERSION', '0.1.0') %}
{% set hash = environ.get('LARCH_HASH', 'f09851e89217b688c9b012da0161cadbc88b5692a9c823b44b83c2c129a5762d') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  {% if src == 'local' %}
  # method 1: use local repo
  path: ../
  {% elif src == 'remote' %}
  # method 2: use online repo
  git_url: https://github.com/matsengrp/larch.git
  git_rev: {{ git_commit }}
  git_submodules: true
  {% elif src == 'release' %}
  # method 3: use release tarball
  url: https://github.com/matsengrp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}
  {% endif %}

build:
  number: 0
  skip: true # [win or osx]

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

    - cmake =3.19.6
    - make
    - openmpi
    - openmpi-mpicc
    - openmpi-mpicxx
    - boost-cpp =1.76
    - automake
    - autoconf
    - libtool
    - yasm
    - ucx
    - zlib

  run:
    - openmpi
    - boost-cpp =1.76
    - ucx
    - zlib

test:
  commands:
    - larch-usher --version
    - ls -lsh

about:
  home: https://github.com/matsengrp/larch
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: 'Phylogenetic tool for exploring tree space of mutation annotated DAG/trees through SPR moves'
  description: |
    Phylogenetic tool for exploring tree space of mutation annotated DAG/trees through SPR moves.
  doc_url: https://github.com/matsengrp/larch/blob/main/README.md
  dev_url: https://github.com/matsengrp/larch

extra:
  recipe-maintainers:
    - matsen
    - davidrich27
    - marybarker
    